### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by TeaBodo** [TeaBodo/loopback_test#1]
- [ ] Fix simulations in all branches
- [ ] Implement PRBS - see ref design, page 37, in XAPP1274
- [ ] Add 400Mbps loopback
- [ ] Add 320Mbps loopback
- [ ] Add strobe mode option
